services:
  - type: web
    name: dineingo-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: cd .. && node backend/dist/server.js
    envVars:
      - key: NODE_ENV
        value: production








