services:
  - type: web
    name: dineingo-backend
    env: node
    buildCommand: cd backend && bun install && bun run build
    startCommand: node src/backend/dist/server.js
    envVars:
      - key: NODE_ENV
        value: production








